### ISSUE TITLE
Define answer behaviour

### ISSUE THREAD

**Issue by benlangfeld** [adhearsion/voicemail#12]
It's probably required to answer for recording to work, but not necessarily desireable to answer before the greeting playback. This behaviour was fiddled with previously but [I'm concerned about how it's currently implemented](https://github.com/adhearsion/voicemail/commit/59a71c71fbcab4d3778c0e0f1f524806feef2534#commitcomment-3987310) and we need to better define this. This is the discussion point.

**Comment by JustinAiken** [comment]
Closed by https://github.com/adhearsion/voicemail/commit/c6cbfeff17dc92e9c5910621f205af0f85c6d31e
