### ISSUE TITLE
Authentication should be configurable

### ISSUE THREAD

**Issue by emcgee** [adhearsion/voicemail#14]
https://github.com/adhearsion/voicemail/blob/develop/lib/voicemail/mailbox_controller.rb#L14

There should be an option that dictates whether pin-based auth is to be used to not.

Many applications many not allow anyone to dial into the VM system without being auth'd by a different mechanism (biometrics, caller id, previous passwords, etc...)

A boolean for  `require_authorization_to_login` could work, unless we want to get crazy and write a pluginable authentication architecture. ;)

**Comment by JustinAiken** [comment]
Alternatively, the auth part of mailbox controller could be split into a seperate auth controller, and the router in an application could decide whether to pass a call to the MailboxController or the AuthController (which would pass to the MailboxController after successful auth)

**Comment by benlangfeld** [comment]
Sounds good to me @JustinAiken, except for the fact that there is a welcome message played before authentication. Can this be considered part of the auth process, and move with it?

**Comment by emcgee** [comment]
I would consider the welcome message as part of the auth process. If someone is skipping auth, they can be responsible for playing an appropriate intro message.

**Comment by JustinAiken** [comment]
Split up [here](https://github.com/adhearsion/voicemail/commit/368aca7192ae8a4fd96e6bbe6c321ae9cf2273d9) - welcome message stayed with the authentication controller.
