### ISSUE TITLE
voicemail.pstore appears in the root directory when running specs

### ISSUE THREAD

**Issue by benlangfeld** [adhearsion/voicemail#2]
As well as tmp/voicemail.pstore

**Comment by lpradovera** [comment]
I could not reproduce this, even with sleep() added to specs in case it was just a transitory issue.
I suppose you just ran "bundle exec rspec"?

**Comment by benlangfeld** [comment]
bundle exec guard -c

Regards,
Ben Langfeld

Em 30 Oct 2012, às 12:49, polysics notifications@github.com escreveu:

I could not reproduce this, even with sleep() added to specs in case it was
just a transitory issue.
I suppose you just ran "bundle exec rspec"?

—
Reply to this email directly or view it on
GitHubhttps://github.com/adhearsion/voicemail/issues/2#issuecomment-9908317.

**Comment by lpradovera** [comment]
Not with that either. Maybe you had an old file somehow?

**Comment by JustinAiken** [comment]
I haven't seen this pop up at all, and I've been working on this gem a lot lately... Closing for now, will reopen if anyone else sees it pop up at any point.
