### ISSUE TITLE
Be consistent about archived vs. saved

### ISSUE THREAD

**Issue by bklang** [adhearsion/voicemail#20]
The API we present uses terms like `next_saved_message`, but in the [Storage::Pstore](https://github.com/adhearsion/voicemail/blob/develop/lib/voicemail/storage_pstore.rb) implementation, the flag is `:archived`.

I think the thing to do is change the Pstore to match the API, but we'll need to document the change and provide a migration script.

**Comment by bklang** [comment]
The same is true with "new" messages, which the Pstore layer internally refers to as "recordings"

**Comment by emcgee** [comment]
+1 and bump to this - the naming scheme should be kept internally consistent. We're mixing and matching `saved` with `archived.`

My vote goes toward `saved` even though I prefer the term archived.

**Comment by wdrexler** [comment]
This will definitely be fixed by the solution to #21. Don't know if we want to do anything about this before 2.0.

**Comment by bklang** [comment]
Addressed in #36
