### ISSUE TITLE
All audio prompts are config values

### ISSUE THREAD

**Issue by wdrexler** [adhearsion/voicemail#25]
We should do this some other way. Suggestions welcomed.

**Comment by bklang** [comment]
I agree with this.  Config is for config, not for an index of audio prompts.  The ultimate solution probably has to do with getting i18n into Adhearsion core.

**Comment by JustinAiken** [comment]
For now, if you set `use_i18n` to true in this plugin, it will use whatever values you put in I18n instead of the prompts set up in the config...

**Comment by wdrexler** [comment]
Now that adhearsion-i18n is a thing, we should probably use that.

**Comment by bklang** [comment]
Fixed by #38
